// Generated by CoffeeScript 1.4.0
(function() {

  describe("Reverser", function() {
    it("reverses a string", function() {
      var string;
      string = "Hello";
      return expect(Reverser.reverse(string)).toEqual(['O', 'l', 'l', 'E', 'h']);
    });
    it("capitalizes vowels", function() {
      var string;
      string = "aeiou";
      return expect(Reverser.reverse(string)).toEqual(['U', 'O', 'I', 'E', 'A']);
    });
    it("lowercases consonants", function() {
      var string;
      string = "BCDFGHJKLMNPQRSTVWXYZ";
      return expect(Reverser.reverse(string)).toEqual(['z', 'y', 'x', 'w', 'v', 't', 's', 'r', 'q', 'p', 'n', 'm', 'l', 'k', 'j', 'h', 'g', 'f', 'd', 'c', 'b']);
    });
    return it("reverses non-letters", function() {
      var string;
      string = "123 456";
      return expect(Reverser.reverse(string)).toEqual(['6', '5', '4', ' ', '3', '2', '1']);
    });
  });

}).call(this);
